version: '{branch}-{build}'

configuration:
  - Debug
  - Release
  - Release_Lite
  - Debug_Lite

skip_commits:
  files:
    - docs/*

before_build:
  - nuget restore

build:
  project: MLAPI.sln
  verbosity: minimal

before_package:
  - cd C:\projects\mlapi
  - powershell "& "".\BuildUnityPackages.ps1"""

artifacts:
  - path: '*.unitypackage'

image: Visual Studio 2017

install: 
  - cd C:\
  - cmd: mkdir testOutput
  - if not exist opencover.zip appveyor DownloadFile "https://github.com/OpenCover/opencover/releases/download/4.6.519/opencover.4.6.519.zip" -FileName opencover.zip
  - 7z x -y opencover.zip -o"C:\opencover" > nul

before_build:
  - cd %appveyor_build_folder%

for:
-
  matrix:
    only:
      - configuration: Debug
  test_script:
  - C:\OpenCover\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI-Tests\bin\Debug\net35\MLAPI-Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI-Tests*]* "
  artifacts:
  - path: 'MLAPI\bin\Debug\net35\MLAPI*'
-
  matrix:
    only:
      - configuration: Debug_Lite
  test_script:
  - C:\OpenCover\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI-Tests\bin\Lite\Debug\net35\MLAPI-Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI-Tests*]* "
  artifacts:
  - path: 'MLAPI\bin\Lite\Debug\net35\MLAPI*'
-
  matrix:
    only:
      - configuration: Release
  test_script:
  - C:\OpenCover\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI-Tests\bin\Release\net35\MLAPI-Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI-Tests*]* "
  artifacts:
  - path: 'MLAPI\bin\Release\net35\MLAPI*'
-
  matrix:
    only:
      - configuration: Release_Lite
  test_script:
  - C:\OpenCover\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"MLAPI-Tests\bin\Lite\Release\net35\MLAPI-Tests.dll" -output:"coverage.xml" -filter:"+[MLAPI*]* -[MLAPI-Tests*]* "
  artifacts:
  - path: 'MLAPI\bin\Lite\Release\net35\MLAPI*'


after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" 